### ISSUE TITLE
Removal of auto generated sources

### ISSUE THREAD

**Issue by amammay** [tmoreira2020/untappd4j#2]
This is a proposal to remove the auto generated sources from version control and only have the schemas generate the pojo's at compile time. More/less trying to open a discussion.

**Comment by amammay** [comment]
here is a branch of what the implementation would be https://github.com/amammay/untappd4j/tree/auto_generated_sources

**Comment by tmoreira2020** [comment]
hey @amammay I like the idea. Can you send me a pull request of it? Make sure your PR doesn't merge logic changes with source formatting changes.

**Comment by amammay** [comment]
@tmoreira2020 Will do, ill get my remote cleaned up and have a pr up soon!

**Comment by amammay** [comment]
https://github.com/tmoreira2020/untappd4j/pull/3

**Comment by tmoreira2020** [comment]
Committed at 0bcaec48513341400613ea6611f31aca533e187a
